env:
  es6: true
  node: true
  mocha: true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
rules:
  "comma-dangle": ["error", "never"]
parserOptions: 
  "parser": ["babel-eslint"]
  "ecmaVersion": [2018]
